version: '3.8'
services:
  app:
    platform: 'linux/amd64'
    env_file: .env.local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
    working_dir: /app
    ports:
      - '3000:3000'
    image: hirica
